apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-secret
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  data:
    - secretKey: cloud
      remoteRef:
        key: velero-secret
        property: cloud