apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # the suffix (-couchdb) is required by the couchdb helm chart
  name: obsidian-couchdb-sh-couchdb
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  data:
    - secretKey: adminUsername
      remoteRef:
        key: obsidian-couchdb-sh-admin
        property: adminUsername
    - secretKey: adminPassword
      remoteRef:
        key: obsidian-couchdb-sh-admin
        property: adminPassword
    - secretKey: cookieAuthSecret
      remoteRef:
        key: obsidian-couchdb-sh-admin
        property: cookieAuthSecret
    - secretKey: erlangCookie
      remoteRef:
        key: obsidian-couchdb-sh-admin
        property: erlangCookie