replicaCount: 1

nameOverride: open-webui-pipelines

persistence:
  enabled: true
  annotations:
    # prevent deletion of persistent volume by argoCD
    argocd.argoproj.io/sync-options: Delete=false
  accessModes:
    - ReadWriteOnce
  size: 4Gi
  storageClass: longhorn

ingress:
  enabled: false

service:
  type: ClusterIP
  port: 9099
  containerPort: 9099

extraEnvVars:
   # manage pipelines manually
  - name: PIPELINES_URLS
    value: ""