crds:
  # -- Install and upgrade CRDs
  install: true
  # -- Keep CRDs on chart uninstall
  keep: true

global:
  env:
    - name: TZ
      value: Asia/Kolkata

configs:
  cm:
    kustomize.buildOptions: --enable-helm
    resource.customizations: |
      argoproj.io/Application:
        health.lua: |
          hs = {}
          hs.status = "Progressing"
          hs.message = ""
          if obj.status ~= nil then
            if obj.status.health ~= nil then
              hs.status = obj.status.health.status
              if obj.status.health.message ~= nil then
                hs.message = obj.status.health.message
              end
            end
          end
          return hs
  params:
    server.insecure: true
    controller.diff.server.side: "true"

dex:
  enabled: false