apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-credentials
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  dataFrom:
    - extract:
        key: cloudflare-tunnel-credentials