apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-store-rb
  namespace: apps-secrets
subjects:
- kind: ServiceAccount
  name: eso-store-sa
  namespace: external-secrets
roleRef:
  kind: ClusterRole
  name: eso-store-role
  apiGroup: rbac.authorization.k8s.io