apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-tenant-secret
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  data:
    - secretKey: config.env
      remoteRef:
        key: minio-tenant-secret
        property: config.env