apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: cluster-secrets
spec:
  provider:
    kubernetes:
      remoteNamespace: apps-secrets
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: external-secrets
      auth:
        serviceAccount:
          name: eso-store-sa
          namespace: external-secrets